### Задание 1
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): 
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. 
Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату 
(то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). 
Произвести расчет как с использованием intercept, так и без.

In [3]:
import numpy as np
x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
b = (np.mean(x*y)-np.mean(x)*np.mean(y))/(np.mean(x**2)-np.mean(x)**2)
b

2.620538882402765

In [5]:
a = np.mean(y) - b*np.mean(x)
a

444.1773573243596

Без интерсепта

In [7]:
x = x.reshape((10,1))
x

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [8]:
y = y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [9]:
B = np.dot(np.linalg.inv(np.dot(x.T,x)),x.T @ y)
B

array([[5.88982042]])

С интерсепта

In [10]:
x = np.hstack([np.ones((10,1)),x])
x

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [12]:
B = np.dot(np.linalg.inv(np.dot(x.T,x)),x.T @ y)
B

array([[444.17735732],
       [  2.62053888]])

### Задание 2
Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [13]:
x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [14]:
def mse_(B1,y=y,x=x,n=10):
    return np.sum((B1*x-y)**2)/n

In [15]:
alpha = 1e-6
alpha

1e-06

In [17]:
B1=0.1

In [19]:
n = 10

In [20]:
for i in range(10000):
    B1 -= alpha*(2/n)*np.sum((B1*x-y)*x)
    if i%5000==0:
        print('Iteration: {i}, B1 = {B1}, mse = {mse}'.format(i=i,B1=B1,mse=mse_(B1)))

Iteration: 0, B1 = 0.25952808, mse = 493237.7212546963
Iteration: 5000, B1 = 5.889820420132673, mse = 56516.85841571943


In [21]:
B0 = 0.1

In [26]:
B1 = 0.1

In [29]:
alpha=5e-5

In [22]:
def mse_(B0,B1,y=y,x=x,n=10):
    return np.sum((B0 + B1*x -y)**2)/n

In [31]:
for i in range(450000):
    y_pred=B0 + B1*x
    B0 -= alpha*(2/n)*np.sum(y_pred-y)
    B1 -= alpha*(2/n)*np.sum((y_pred-y)*x)
    if i%30000==0:
        print('Iteration: {i}, B0={B0}, B1= {B1}, mse = {mse}'.format(i=i,B0=B0,B1=B1,mse=mse_(B0,B1)))

Iteration: 0, B0=444.17735700457126, B1= 2.620538884756549, mse = 6470.41420117666
Iteration: 30000, B0=444.1773571749486, B1= 2.6205388835024963, mse = 6470.414201176657
Iteration: 60000, B0=444.1773572545476, B1= 2.6205388829166125, mse = 6470.414201176658
Iteration: 90000, B0=444.17735729174746, B1= 2.620538882642805, mse = 6470.414201176658
Iteration: 120000, B0=444.1773573091013, B1= 2.6205388825150733, mse = 6470.414201176659
Iteration: 150000, B0=444.1773573171897, B1= 2.6205388824555387, mse = 6470.41420117666
Iteration: 180000, B0=444.1773573210606, B1= 2.6205388824270472, mse = 6470.414201176654
Iteration: 210000, B0=444.1773573227659, B1= 2.6205388824144955, mse = 6470.41420117666
Iteration: 240000, B0=444.17735732323933, B1= 2.6205388824110107, mse = 6470.414201176658
Iteration: 270000, B0=444.17735732323933, B1= 2.6205388824110107, mse = 6470.414201176658
Iteration: 300000, B0=444.17735732323933, B1= 2.6205388824110107, mse = 6470.414201176658
Iteration: 330000, B0=444.177

### Задание 3
В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица 
значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

Оценка по Стьюденту учитывает неполноту статистической выборки, т.е количество выборки очень мало